/*Generated by KISSY Module Compiler*/
if(KISSY.Loader){
KISSY.config('modules', {
'overlay': {requires: ['om','vent','omponent']},
'event': {requires: ['vent/ie']},
'event/base': {requires: ['om']},
'event/ie': {requires: ['vent/base','om/ie','a']},
'switch': {requires: ['om','ibase/position']},
'dom/ie': {requires: ['a']},
'page/run': {requires: ['witch','verlay',window["xx"] ? "x" : "y"]}
});
}
