/*Generated by KISSY Module Compiler*/
if(KISSY.Loader){
KISSY.config('modules', {
'dom': {requires: ['ua']},
'overlay': {requires: ['dom', 'event']},
'event': {requires: ['dom', 'ua']},
'switch': {requires: ['dom', 'uibase/position']},
'page/run': {requires: ['switch']}
});
}
