/*Generated by KISSY Module Compiler*/
if(KISSY.Loader){
KISSY.config('modules', {
'overlay': {requires: ['dom', 'event', 'component']},
'event': {requires: ['event/ie']},
'event/base': {requires: ['dom']},
'event/ie': {requires: ['event/base', 'dom/ie', 'ua']},
'switch': {requires: ['dom', 'uibase/position']},
'dom/ie': {requires: ['ua']},
'page/run': {requires: ['switch', 'overlay']}
});
}
