/*Generated by KISSY Module Compiler*/
if(KISSY.Loader){
KISSY.config('modules', {
'page': {requires: ['switch']},
'dom': {requires: ['ua']},
'overlay': {requires: ['dom', 'event']},
'event': {requires: ['dom', 'ua']},
'switch': {requires: ['dom', 'uibase']}
});
}
